spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: user
    password: password
    jpa:
      hibernate.ddl-auto: update
server:
  port: 8083
#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
#    username: user
#    password: password
#  jpa:
#    hibernate.ddl-auto: update